### ISSUE TITLE
Bump required framework version

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt-contrib-languagePicker#3]
This will need to be raised to `^2.0.11` because, at the very least, the `equals` Handlebars helper doesn’t exist in previous releases.

**Comment by lc-thomasberger** [comment]
fixed in https://github.com/adaptlearning/adapt-contrib-languagePicker/commit/70d7c179b027d90120289f92c317c4a5692f8176

thanks @tomgreenfield
