### ISSUE TITLE
Bug: Resource options not updating on language change

### ISSUE THREAD

**Issue by sharpb** [adaptlearning/adapt-contrib-languagePicker#7]
I've created a multi-language course which has two resource links in the drawer.  When I change the language the resource links do not update to the new language - they stay in the language that was selected on the language picker screen.  I'm using adapt-contrib-resources version 2.0.4.

**Comment by lc-thomasberger** [comment]
PR's:
https://github.com/adaptlearning/adapt_framework/pull/1251
https://github.com/adaptlearning/adapt-contrib-resources/pull/43

**Comment by moloko** [comment]
@sharpb we need one more review on https://github.com/adaptlearning/adapt-contrib-resources/pull/43 - any chance you could oblige? then we can get this merged and closed off

**Comment by moloko** [comment]
not to worry, now done and merged via https://github.com/adaptlearning/adapt-contrib-resources/commit/b9bb18c3d8a0fa335cb085711a1d7a2302922812
