### ISSUE TITLE
Ability to bypass language picker

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt-contrib-languagePicker#8]
It would be useful to have a flag in the configuration which allows to bypass the language picker prompt and takes the user directly to the `_defaultLanguage`.

**Comment by moloko** [comment]
https://github.com/adaptlearning/adapt-contrib-languagePicker/pull/13

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-languagePicker/commit/5f205e38ac6f5921502c5a346398d8e7b005959b
