### ISSUE TITLE
Missing data-order support for sorting navigation

### ISSUE THREAD

**Issue by kirsty-hames** [adaptlearning/adapt-contrib-languagePicker#83]
### Subject of the issue
`.nav__languagepicker-btn` is missing the `data-order` attribute as per other navigation buttons in Adapt (see core PR for ref https://github.com/adaptlearning/adapt-contrib-core/pull/61)

When changing languages via the language picker menu, navigation buttons switch places when the new language loads.

### Your environment
* v5.28.15 FW
* v5.2.3 languagePicker
I expect this will apply to both latest FW and languagePicker but I'll confirm.

**Comment by oliverfoster** [comment]
Fixed in https://github.com/adaptlearning/adapt-contrib-languagePicker/pull/89
